name: CI

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Tools
        run: sudo apt-get -y install ninja-build

      - name: Init & Update submodules
        run: git submodule update --init --recursive

      - name: Configure CMake
        run: cmake -G "Ninja" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target dvm

  Windows-MSVC:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Init & Update submodules
        run: git submodule update --init --recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target dvm

  Windows-MinGW:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Init & Update submodules
        run: git submodule update --init --recursive

      - name: Configure CMake
        run: cmake -G "MinGW Makefiles" -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target dvm

  MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Tools
        run: brew install ninja

      - name: Init & Update submodules
        run: git submodule update --init --recursive

      - name: Configure CMake
        run: cmake -G "Ninja" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target dvm
